version: "3"
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  hystrix_dashboard:
    image: kennedyoliveira/hystrix-dashboard
    ports:
      - "8000:7979"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  hydra_router:
    image: flywheelsports/hydra-router:1.6.8
    depends_on:
      - redis
    ports:
      - "5353:5353"
    extra_hosts:
      - "host:172.28.128.7"
  so_service:
    build:
      context: ./sale-order
      dockerfile: Dockerfile
    image: sapps:sale-order-service-0.0.1
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis://redis:6379/15
  do_service:
    build:
      context: ./delivery-order
      dockerfile: Dockerfile
    image: sapps:delivery-order-service-0.0.1
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis://redis:6379/15
  inv_service:
    build:
      context: ./invoice
      dockerfile: Dockerfile
    image: sapps:invoice-service-0.0.1
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis://redis:6379/15
  pay_service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: sapps:payment-service-0.0.1
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis://redis:6379/15
